### ISSUE TITLE
Justify text in Card body

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [iced-rs/iced_aw#153]
I was looking for a way to left-justify text in Card body (used inside a Modal as per modal example).
I couldn't find any method in the docs, and it looks like the text is center justified by default?
thanks

**Comment by genusistimelord** [comment]
hmm the Body is set to align via 
```rust
body.align(Alignment::Start, Alignment::Start, size);
```
However the Header and Footer are set to align Vertical as Alignment::Center.

The body also moves the contents based on the Padding as well. 

The Modal stuff Always Centers its overlay widgets.

**Comment by andrewdavidmackenzie** [comment]
Sorry, I'm a bit of a noob to Iced.... not sure where I can find a align() method.
Can't see it on Card, or Text.

My existing code is:
```
        Modal::new(self.show_modal, content, || {
            Card::new(
                Text::new(self.modal_content.clone().0),
                Text::new(self.modal_content.clone().1),
            )
            .foot(
                Row::new()
                    .spacing(10)
                    .padding(5)
                    .width(Length::Fill)
                    .push(
                        Button::new(Text::new("Ok")
                            .horizontal_alignment(Horizontal::Center))
                            .width(Length::Fill)
                            .on_press(Message::CloseModal),
                    ),
            )
            .max_width(300.0)
            .into()
        })
        .backdrop(Message::CloseModal)
        .on_esc(Message::CloseModal)
        .into()
```

**Comment by genusistimelord** [comment]
oh I am just saying by default the Body is already at that align. there is no way to actually set this yourself for the Body. However for other widgets inside of the body you can have them align internally if they support align or horizontal align.

For Text https://docs.rs/iced_native/0.10.1/iced_native/widget/text/struct.Text.html
you will see there is a [horizontal_alignment](https://docs.rs/iced_native/0.10.1/iced_native/widget/text/struct.Text.html#method.horizontal_alignment) and a [vertical_alignment](https://docs.rs/iced_native/0.10.1/iced_native/widget/text/struct.Text.html#method.vertical_alignment)


If there is a Visual issue with card due to the default align Please upload a image highlighting the issue.

**Comment by andrewdavidmackenzie** [comment]
Thanks for your help.
