### ISSUE TITLE
NumberInput panics when overwriting selected number

### ISSUE THREAD

**Issue by Kaiden42** [iced-rs/iced_aw#18]
The number input panics when selected text is overwritten.
```
thread 'main' panicked at 'slice index starts at 1 but ends at 0', /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1735:36

```

Steps to reproduce this issue:
1. Create a NumberInput that starts with a value like `5` for example.
2. Select `5` in the TextInput part of the NumberInput.
3. Type another number to overwrite the selection.
4. Panic

Maybe this is caused by the text being empty.

**Comment by genusistimelord** [comment]
this is caused by replace_range not liking that end and start are in reverse. So the fix is to swap them when start is greater than end. Also to add a bounds check here too so if you do attempt to Select outside of the bounds it wont panic as well. 

https://github.com/genusistimelord/iced_aw/commit/bbbbd74901aa89c9cc68fe7b5214aa212b44df5c

I can make these updates and push them once my Selection list is added.

**Comment by Kaiden42** [comment]
If you could do this, I would be very appreciative. :slightly_smiling_face: 

I have just merged your other PR.
