### ISSUE TITLE
Mandatory copy trait makes it impossible to use custom message with additional parameters

### ISSUE THREAD

**Issue by daniel-prause** [iced-rs/iced_aw#210]
Hi there!

I've stumbled upon a problem regarding the number_input widget.
Since for the callback function the "Copy" trait is mandatory, it is impossible for me to achieve something like this, which works perfectly fine for the iced base library:

```
iced::widget::TextInput::new(
                            humanize_string(&key).as_str(),
                            field_value.as_str(),
                        )
                        .on_input(move |value: String| {
                            Message::ConfigValueChanged(
                                screen_key.clone(),
                                key.clone(),
                                exchange_format::ConfigParam::Password(value),
                            )
                        })
```

Since the compiler asks me to use move and since String does not implement the copy trait, I can't use a custom "Message" with a String parameter.
screen_key and screen are Strings.

**Comment by genusistimelord** [comment]
so the thing here is Copy was chosen because its the fastest method for numbers. since this only deals with numbers. 

So in order to make what you want we would need to implement Clone which would half the speed of the operations. If this doesn't affect anything majorly we can do this but just to support the possibility of doing what you want. However There is another way to do what you want without affecting the Speed of the widget.

```rust
 pub fn view<F>(&self, id: usize, min: V, max: V, step: V, on_change: F) -> Element<M>
    where
        F: 'static + Fn((usize, NumInputMessage<V>)) -> M + Copy,
        V: 'static,
        M: 'static,
    {
        Element::new(
            NumberInput::new(self.value, max, NumInputMessage::Change)
                .step(step)
                .min(min)
                .style(NumberInputStyles::custom(araiseal_styles::CustomNumInput))
                .width(Length::Shrink),
        )
        .map(move |i| on_change((id, i)))
    }
```
    
The above shows how you can map the widgets output to custom Messages without affecting the way the underlying widget was designed. however, generally I would not Expect all widgets to have the same capabilities or expect it since they are all made to do very specific tasks.
